// <auto-generated />
namespace gMenu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _3rd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rd));
        
        string IMigrationMetadata.Id
        {
            get { return "201403040523205_3rd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
