// <auto-generated />
namespace gMenu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1st : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1st));
        
        string IMigrationMetadata.Id
        {
            get { return "201403031010450_1st"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
